### ISSUE TITLE
Not working with sass-loader?

### ISSUE THREAD

**Issue by pklicnik** [istarkov/minimal-example-for-babel-plugin-webpack-loaders#4]
Trying to use this example as a starting point for integrating with a Jest build. I have SASS files in my project, so I wanted to use `sass-loader`. The `sass-loader` doesn't seem to be taking because it's choking at runtime:

```
SyntaxError: /Development/test/minimal-example-for-babel-plugin-webpack-loaders/test.scss: Unexpected token (1:3)
> 1 | h2 {
    |    ^
  2 |   margin: 0;
```

Steps I took:
1) `npm install node-sass sass-loader --save-dev`

2) Updated `example.js` to import the scss file:

```
// example.js
import css from './example.css';
import scss from './test.scss';
console.log('css-modules result:', css); // eslint-disable-line no-console
console.log('css-modules result:', scss); // eslint-disable-line no-console
```

3) Updated the `webpack.config.js` file to include `sass-loader` and updated the test regex

```
    loaders: [
      {
        test: /\.(s)*css$/,
        loaders: [
          'style-loader',
          'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]--[hash:base64:5]',
          'sass-loader',
          'postcss-loader'
        ],
      },
    ],
```

Is this a bug or am I missing something very obvious?

**Comment by istarkov** [comment]
sass loader is used in all examples and tests in the main project.
So first error in your example is postcss must be placed before sass-loader

**Comment by pklicnik** [comment]
Swapped the order:

```
// webpack.config.js css-modules loader example
module.exports = {
  output: {
    // YOU NEED TO SET libraryTarget: 'commonjs2'
    libraryTarget: 'commonjs2',
  },
  module: {
    loaders: [
      {
        test: /\.(s)*css$/,
        loaders: [
          'style-loader',
          'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]--[hash:base64:5]',
          'postcss-loader',
          'sass-loader'
        ],
      },
    ],
  },
};
```

But still same error.

The main examples are using the `ExtractTextPlugin`. Is that a requirement?

**Comment by istarkov** [comment]
Just part of main examples uses ExtractTextPlugin, not a requirement. Why u use capture in regexp?

**Comment by pklicnik** [comment]
No particular reason (copied it from elsewhere), but it shouldn't matter. Still failing:

```
// webpack.config.js css-modules loader example
module.exports = {
  output: {
    // YOU NEED TO SET libraryTarget: 'commonjs2'
    libraryTarget: 'commonjs2',
  },
  module: {
    loaders: [
      {
        test: /\.s*css$/,
        loaders: [
          'style-loader',
          'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]--[hash:base64:5]',
          'postcss-loader',
          'sass-loader'
        ],
      },
    ],
  },
};
```

**Comment by istarkov** [comment]
I don't know what are you doing wrong here the PR https://github.com/istarkov/minimal-example-for-babel-plugin-webpack-loaders/pull/5 with your example. 

It works as expected.

```
npm run start
# output
# css-modules result: { main: 'example__main--zYOjd', item: 'example__item--W9XoN' }
# css-modules result: { main: 'example__main--3em0Y', item: 'example__item--2bZ0j' }
```

**Comment by pklicnik** [comment]
You branch worked. The only difference I could find between your branch and my local copy was the version of `webpack` I had installed was a few versions older for some reason - `1.12.6` vs `1.12.14` which I got when I ran `npm install` on your example.
